### ISSUE TITLE
Build steps in readme not repeatable

### ISSUE THREAD

**Issue by jcreager** [snarlysodboxer/hambone#1]
Hey, this looks pretty good so far, but I'm having trouble building from source.  It looks like the protobufs need to be compiled before running go build.  Can you also provide instructions for building the protobufs in the readme?

When I run `go build -tags debug -o hambone main.go && ./hambone` I get:

```
main.go:5:2: cannot find package "github.com/snarlysodboxer/hambone/generated" in any of:
	/Users/<user>/go/src/github.com/snarlysodboxer/hambone/vendor/github.com/snarlysodboxer/hambone/generated (vendor tree)
	/usr/local/go/src/github.com/snarlysodboxer/hambone/generated (from $GOROOT)
	/Users/<user>/go/src/github.com/snarlysodboxer/hambone/generated (from $GOPATH)
```

I attempted this command: `protoc ./protos/hambone.proto -out=generated`:

```
vendor/annotations.proto: File not found.
protos/hambone.proto: Import "vendor/annotations.proto" was not found or had errors.
```

If I try to compile annotations.proto directly with `protoc annotations.proto -out=.` I get:

```
google/api/http.proto: File not found.
annotations.proto: Import "google/api/http.proto" was not found or had errors.
annotations.proto:33:3: "HttpRule" is not defined.
```

How are you compiling the protos?

**Comment by snarlysodboxer** [comment]
Thanks for catching this. The script `./bin/build-stubs.sh` is for building the generated code, however I decided it makes sense to commit the generated code, so you should now be able to pull in my latest changes and it'll just work.

Also, see updated `README.md` and Docker instructions if you want.

Let me know if you have any more issues.

**Comment by snarlysodboxer** [comment]
Let me know if you're still having any issues @jcreager. :)
